name: Cypress Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, safari]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }} --parallel --record --key <your-cypress-dashboard-key>

      - name: Upload Cypress reports
        if: always()
        run: |
          mkdir -p reports
          mv cypress/videos reports/
          mv cypress/screenshots reports/
          tar -czf reports.tar.gz reports/
          upload-artifact --name cypress-reports --path reports.tar.gz
